config/routes.rb
IVGCWholeSale::Application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get "services/reseller"
    get "services/wholesale"
    get "voip_resellers/voipResellerSignUp"
    post "voip_resellers/voipResellerSignUp"
    get "voip_resellers/thanksForSigningUp"

    get "rates/index"
    get "rates/displayRate"
    post "rates/displayRate"

    get "admin/accountInfo"
    post "admin/accountTerminate"
    get "admin/accountList"
    post "admin/viewTickets"
    get "admin/viewTickets"
    get "admin/index"
    resources :admin

    post "/responses/new"
    resources :responses

    post "tickets/new"
    get "tickets/viewResponses"
    resources :tickets

    get "accounts/instructions"
    post "accounts/forgotPasswordSubmit"
    get "accounts/forgotPasswordSubmit"
    post "accounts/forgotPassword"
    get "accounts/forgotPassword"
    get "accounts/displayWU"
    get "accounts/displayBank"
    get "accounts/bankDescription"
    get "accounts/paypalPayment"
    get "accounts/creditCardPayment"
    post "accounts/wuPaymentSubmit"
    get "accounts/wuPaymentSubmit"
    post "accounts/bankTransferSubmit"
    get "accounts/bankTransferSubmit"
    get "accounts/wuPayment"
    get "accounts/bankTranfers"
    post "accounts/paymentConfirm"
    get "accounts/paymentConfirm"
    post "accounts/addCredits"
    get "accounts/addCredits"
    get "accounts/addCreditsSubmit"
    post "accounts/addCreditsSubmit"
    get "accounts/creditAdded"
    get "accounts/deleteIP"
    post "accounts/updateIP"
    get "accounts/updateIP"
    get "accounts/manageIP"
    get "accounts/viewCDR"
    post "accounts/formatDate"
    get "accounts/updateAccount"
    get "accounts/doUpdate"
    post "accounts/doUpdate"

    get "signups/signUp"
    post "signups/signUp"

    get "contact_us/contactUs"
    post "contact_us/contactUs"
    get "contact_us/thanksForContacting"

    get "voip_resellers/voipResellerSignUp"
    get "sessions/destroy"
    resources :home, only: :index
    resources :sessions
    resources :accounts
    resources :signups
    resources :about_us
    resources :services
    resources :rates do
      collection { post :import }
    end  
    resources :contact_us
    resources :voip_resellers

    root :to => 'sessions#new'

  end
  match '', to: redirect("/#{I18n.default_locale}")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div class="slider-wrapper theme-default">
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40480808-9', 'ivgc.net');
      ga('send', 'pageview');

  </script>
  <div id="slider" class="nivoSlider">
    <%= image_tag("slide1.jpg") %>
    <%= image_tag("slide2.jpg") %>
    <%= image_tag("slide3.jpg") %>
    <%= image_tag("slide4.jpg") %>
  </div>
</div>
<div class="left_section" id="left_section_home">
  <section>
    <header style="text-align:justify;font-size:17px;"><%= t "home.index.voip" %></header>
    <ul>
      <li><%= t ".vline1" %></li>
      <li><%= t ".vline2" %></li>
      <li><%= t ".vline3" %></li>
    </ul>
    <% if !session[:current_login] %>
      <article><%= link_to t(".sign_up_res"), voip_resellers_path %></article>
    <% end %>
  </section>
</div>

<div class="right_section" id="right_section_home">
  <section>
    <header style="text-align:justify;font-size:17px;"><%= t "home.index.wholesale" %></header>
    <ul>
      <li><%= t ".wline1" %></li>
      <li><%= t ".wline2" %></li>
      <li><%= t ".wline3" %></li>
    </ul>
    <% if !session[:current_login] %>
      <article><!--%= link_to t(".sign_up_whole"), signups_path %--><%= link_to t(".sign_up_whole"), voip_resellers_path %></article>
    <% end %>
  </section>
</div>
<%= javascript_include_tag "olark_contact_us" %>