config/routes.rb
IVGCWholeSale::Application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get "services/reseller"
    get "services/wholesale"
    get "voip_resellers/voipResellerSignUp"
    post "voip_resellers/voipResellerSignUp"
    get "voip_resellers/thanksForSigningUp"

    get "rates/index"
    get "rates/displayRate"
    post "rates/displayRate"

    get "admin/accountInfo"
    post "admin/accountTerminate"
    get "admin/accountList"
    post "admin/viewTickets"
    get "admin/viewTickets"
    get "admin/index"
    resources :admin

    post "/responses/new"
    resources :responses

    post "tickets/new"
    get "tickets/viewResponses"
    resources :tickets

    get "accounts/instructions"
    post "accounts/forgotPasswordSubmit"
    get "accounts/forgotPasswordSubmit"
    post "accounts/forgotPassword"
    get "accounts/forgotPassword"
    get "accounts/displayWU"
    get "accounts/displayBank"
    get "accounts/bankDescription"
    get "accounts/paypalPayment"
    get "accounts/creditCardPayment"
    post "accounts/wuPaymentSubmit"
    get "accounts/wuPaymentSubmit"
    post "accounts/bankTransferSubmit"
    get "accounts/bankTransferSubmit"
    get "accounts/wuPayment"
    get "accounts/bankTranfers"
    post "accounts/paymentConfirm"
    get "accounts/paymentConfirm"
    post "accounts/addCredits"
    get "accounts/addCredits"
    get "accounts/addCreditsSubmit"
    post "accounts/addCreditsSubmit"
    get "accounts/creditAdded"
    get "accounts/deleteIP"
    post "accounts/updateIP"
    get "accounts/updateIP"
    get "accounts/manageIP"
    get "accounts/viewCDR"
    post "accounts/formatDate"
    get "accounts/updateAccount"
    get "accounts/doUpdate"
    post "accounts/doUpdate"

    get "signups/signUp"
    post "signups/signUp"

    get "contact_us/contactUs"
    post "contact_us/contactUs"
    get "contact_us/thanksForContacting"

    get "voip_resellers/voipResellerSignUp"
    get "sessions/destroy"
    resources :home, only: :index
    resources :sessions
    resources :accounts
    resources :signups
    resources :about_us
    resources :services
    resources :rates do
      collection { post :import }
    end  
    resources :contact_us
    resources :voip_resellers

    root :to => 'sessions#new'

  end
  match '', to: redirect("/#{I18n.default_locale}")
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  #before_filter :validateAdminLoggedIn

  def index
    @responses = Response.all
  end

  def show
    begin
      @response = Response.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'No response!'
      redirect_to '/responses'
    end
  end

  def new
     @response = Response.new
     session[:id] = params[:id]
  end

  def edit
    @response = Response.find(params[:id])
  end

  def update
    @response = Response.find(params[:id])
    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @response = Response.new(params[:response])
    @response.ticket_id = session[:id]
    respond_to do |format|
      if @response.save
        @ticket = Ticket.where(:id => @response.ticket_id)[0]
        @ticket.update_attributes(:responded_to => true)
        format.html { redirect_to '/responses' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to response_url
  end
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@response.errors.count, "error") %> prohibited this ticket from being saved:</h3>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<%= render 'form' %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Associated ticket</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |r| %>
  <tr>
    <td><%= r.description %></td>
    <td><%= Ticket.where(:id => r.ticket_id)[0].title rescue nil %>
    <td><%= link_to 'Show', r %></td>
    <td><%= link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Update', edit_response_path(r) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/responses/new.html.erb
<%= render 'form' %>

app/views/responses/show.html.erb
<p>
  <b>Description:</b>
  <%= @response.description %>
</p>


<%= link_to 'Back', tickets_path %>